### ISSUE TITLE
Lack of attribution, your website's use of OpenStreetMap data

### ISSUE THREAD

**Issue by govvin** [miguel123-gis/bikelanes-map#1]
I just noticed that you've been using OpenStreetMap data, and simply referring to it in your layers as "mapped bike lanes" without attributing your source.

![image](https://user-images.githubusercontent.com/5821688/120136733-6892ac80-c205-11eb-8bed-bae54465f084.png)

You might think you're already attributing OSM in some of your tile layers, but that's incorrect because the tiles are licensed separately from the OSM data layer you're displaying on top of the tiles.

For sure, the OSM contributors and the OSM Foundation will appreciate it very much if you follow the OpenStreetMap license attribution requirement. You may read more about it here: https://openstreetmap.org/wiki/Community_attribution_advice

The community looks forward to your prompt action on this matter.  If you have questions, please don't hesitate to ask.

**Comment by miguel123-gis** [comment]
Hi Sir Erwin! The mapped bike lanes layer is from a Google My Maps and not from OSM. :D

https://www.google.com/maps/d/u/0/edit?mid=1MUEnacNSB60OpJQG0ViAnzJ6ECrA5z7p&ll=14.58936632944314%2C121.03263774951976&z=13

Thank you!

Sincerely, 

Miguel Imperial 

      

From: Win Olario
Sent: Monday, May 31, 2021 11:46 AM
To: miguel123-gis/bikelanes-map
Cc: Subscribed
Subject: [miguel123-gis/bikelanes-map] Lack of attribution, your website's use of OpenStreetMap data (#1)

I just noticed that you've been using OpenStreetMap data, and simply referring to it in your layers as "mapped bike lanes" without attributing your source.

You might think you're already attributing OSM in some of your tile layers, but that's in correct because the tiles are licensed separately from the OSM data layer you're displaying on top of the tiles.
For sure, the OSM contributors and the OSM Foundation will appreciate it very much if you follow the OpenStreetMap license attribution requirement. You may read more about it here: https://openstreetmap.org/wiki/Community_attribution_advice
The community looks forward to your prompt action on this matter. If you have questions, please don't hesitate to ask.

**Comment by govvin** [comment]
Hi Miguel. 

Crowd-sourced? Funny, because some of my street traps showed up. ;)

**Comment by miguel123-gis** [comment]
Ah. Sige po. Should I still put attribution to OSM? Parang “The Mapped Bike Lanes layer is from this Google My Maps and OpenStreetMap contributors”

Sincerely, 

Miguel Imperial

**Comment by govvin** [comment]
@miguel123-gis , if that's the case, the attribution for your tile layers is sufficient. You only need additional attribution if you're using OSM data directly.

Thank you for the clarification, and sorry for the bother.
